version: '3.8'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - ./server/.env 
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - notecode-network
    volumes:
      - ./server:/server-app
      - /server-app/node_modules
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    env_file:
      - ./client/.env
    ports: 
      - "3000:3000"
    volumes: 
      - ./client:/client-app
      - /client-app/node_modules
    restart: always

  mongodb:
    image: mongo:7.0
    container_name: notecode-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: notecode
    volumes:
      - mongodb_data:/data/db
      - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - notecode-network

  mongo-express:
    image: mongo-express:latest
    container_name: notecode-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - notecode-network

volumes:
  mongodb_data:

networks:
  notecode-network:
    driver: bridge